Repository projectdiscovery/ratelimit, pull requests merged in 2022-12, with the labels that each got.

#18 adds mulitlimiter + adaptive ratelimiter
  README.md
  adaptive_ratelimit_test.go
  example/main.go
  keyratelimit.go
  keyratelimit_test.go
  ratelimit.go
Labels: Type: Enhancement

#21 Remove redundant push event
  .github/workflows/build-test.yml
  .github/workflows/lint-test.yml
Labels: Type: Maintenance

#20 Add Stop method
  go.mod
  go.sum
  keyratelimit.go
  ratelimit.go
Labels: Type: Bug
